### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. -> Maybe because of an empty array?

### ISSUE THREAD

**Issue by Arr1x** [Synthesis-Collective/HalgarisConsistentRPGLoot#11]
The patcher aborts with the following error: 

```
[92.6][HalgarisConsistentRPGLoot] System.IndexOutOfRangeException: Index was outside the bounds of the array.
[92.6][HalgarisConsistentRPGLoot]    at HalgarisRPGLoot.Extensions.RandomItem[T](T[] itms) in C:\Users\Arrix\AppData\Local\Temp\Synthesis\690bdcc1-24d5-4ab6-8dd7-c2992fb8b38f\Git\0526d240-106a-4bb3-9fc5-e588fd686ca5\Runner\HalgarisRPGLoot\Extensions.cs:line 16
[92.6][HalgarisConsistentRPGLoot]    at HalgarisRPGLoot.Extensions.Repeatedly[T](Func`1 f)+MoveNext() in C:\Users\Arrix\AppData\Local\Temp\Synthesis\690bdcc1-24d5-4ab6-8dd7-c2992fb8b38f\Git\0526d240-106a-4bb3-9fc5-e588fd686ca5\Runner\HalgarisRPGLoot\Extensions.cs:line 22
[92.6][HalgarisConsistentRPGLoot]    at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
[92.6][HalgarisConsistentRPGLoot]    at System.Linq.Enumerable.EnumerablePartition`1.ToArray()
[92.6][HalgarisConsistentRPGLoot]    at HalgarisRPGLoot.Extensions.Shuffle[T](IEnumerable`1 coll) in C:\Users\Arrix\AppData\Local\Temp\Synthesis\690bdcc1-24d5-4ab6-8dd7-c2992fb8b38f\Git\0526d240-106a-4bb3-9fc5-e588fd686ca5\Runner\HalgarisRPGLoot\Extensions.cs:line 27
[92.6][HalgarisConsistentRPGLoot]    at HalgarisRPGLoot.WeaponAnalyzer.GenerateEnchantment(ResolvedListItem`1 item, String rarityName, Int32 rarityEnchCount)
[92.6][HalgarisConsistentRPGLoot]    at HalgarisRPGLoot.WeaponAnalyzer.Generate() in C:\Users\Arrix\AppData\Local\Temp\Synthesis\690bdcc1-24d5-4ab6-8dd7-c2992fb8b38f\Git\0526d240-106a-4bb3-9fc5-e588fd686ca5\Runner\HalgarisRPGLoot\WeaponAnalyer.cs:line 149
[92.6][HalgarisConsistentRPGLoot]    at HalgarisRPGLoot.Program.RunPatch(IPatcherState`2 state) in C:\Users\Arrix\AppData\Local\Temp\Synthesis\690bdcc1-24d5-4ab6-8dd7-c2992fb8b38f\Git\0526d240-106a-4bb3-9fc5-e588fd686ca5\Runner\HalgarisRPGLoot\Program.cs:line 47
[92.6][HalgarisConsistentRPGLoot]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
[92.6][HalgarisConsistentRPGLoot] --- End of stack trace from previous location ---
[92.6][HalgarisConsistentRPGLoot]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
[92.6][HalgarisConsistentRPGLoot]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
[92.6][HalgarisConsistentRPGLoot]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
```

and 

```
[92.9][HalgarisConsistentRPGLoot] Error while running
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)
[92.9] Finished patcher run.
[log-20210624.txt](https://github.com/Synthesis-Collective/HalgarisConsistentRPGLoot/files/6712169/log-20210624.txt)

```

On the Discord theSkyseS and Noggog assumed that the accessed array may be empty and thus leading to the error. 
The whole log: [log-20210624.txt](https://github.com/Synthesis-Collective/HalgarisConsistentRPGLoot/files/6712172/log-20210624.txt)

**Comment by EzioTheDeadPoet** [comment]
I fixed an out of bounds error a while ago. 🤔 
Someone else still got it due to errors in his setup. 
I recommend letting xEdit look for errors and cyclic leveled lists.

**Comment by EzioTheDeadPoet** [comment]
caused by confliting mods.
