### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by Madpaddy** [Synthesis-Collective/HalgarisConsistentRPGLoot#15]
Getting this error when I run the patcher at around 26.2 sec.... Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by EzioTheDeadPoet** [comment]
This log sadly has no useful information. Getting the full text log might be helpful. 

But here are things to try:

- Make sure your leveled lists, armors and weapons are setup correctly. 
- Restart Synthesis.
- Update to the latest Synthesis version.
- set the patcher to use the `tag` versioning an select the highest version.
- set mutagen and synthesis version on match.

**Comment by Madpaddy** [comment]
Ill give that a go cheers...

**Comment by Madpaddy** [comment]
Cant post new error log its to big...

**Comment by EzioTheDeadPoet** [comment]
delete the file rerun synthesis and drag and drop the file. 

I will not be able to look into it tho as I am on holidays rn.

**Comment by Madpaddy** [comment]
Thats ok mate ill leave it for now, have a great holiday...

**Comment by EzioTheDeadPoet** [comment]
should be fixed in with version 1.4.0.
