### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zazanels** [Synthesis-Collective/HalgarisConsistentRPGLoot#27]
System.AggregateException: One or more errors occurred. (One or more errors occurred. (LLCT List<Mutagen.Bethesda.Skyrim.ILeveledItemEntryGetter> had an overflow.  Too many items to fit in the counter subrecord: 258))
 ---> System.AggregateException: One or more errors occurred. (LLCT List<Mutagen.Bethesda.Skyrim.ILeveledItemEntryGetter> had an overflow.  Too many items to fit in the counter subrecord: 258)
 ---> SubrecordException  => SublistWeaponGreatswordDaedricBest05 (000F12:Skyrim.esm<LeveledItem>) => LLCT: LLCT List<Mutagen.Bethesda.Skyrim.ILeveledItemEntryGetter> had an overflow.  Too many items to fit in the counter subrecord: 258 System.OverflowException: LLCT List<Mutagen.Bethesda.Skyrim.ILeveledItemEntryGetter> had an overflow.  Too many items to fit in the counter subrecord: 258
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Mutagen.Bethesda.Plugins.Binary.Streams.MutagenWriter.Write(Int32 i, Byte length)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ListBinaryTranslation`1.WriteWithCounter(MutagenWriter writer, IReadOnlyList`1 items, RecordType counterType, BinaryMasterWriteDelegate`1 transl, Byte counterLength, Boolean writeCounterIfNull, Nullable`1 endMarker, RecordTypeConverter recordTypeConverter)
   --- End of inner exception stack trace ---   at Mutagen.Bethesda.Skyrim.LeveledItemBinaryWriteTranslation.Write(MutagenWriter writer, ILeveledItemGetter item, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.LeveledItem.Mutagen.Bethesda.Plugins.Binary.Translations.IBinaryItem.WriteToBinary(MutagenWriter writer, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.<>c__DisplayClass18_0`1.<WriteGroupParallel>b__0(IEnumerable`1 cutItems, ParallelLoopState state, Int64 counter)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__2(Int32 i, ParallelLoopState state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`3 body)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.WriteGroupParallel[T](ISkyrimGroupGetter`1 group, Int32 targetIndex, Stream[] streamDepositArray, WritingBundle bundle, ParallelWriteParameters parallelParam)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.<>c__DisplayClass17_0.<WriteParallel>b__46()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0(Object& state, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ParallelWriteParameters parallelParam, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, ParallelWriteParameters parallelParam, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem, ParallelWriteParameters parallelWriteParams)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 641
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456

**Comment by EzioTheDeadPoet** [comment]
Looks like a system/configuration issue. Please try to use the latest version.
Closing this now since this issue is related to an old codebase that is now completely overhauled.
